### ISSUE TITLE
不蒜子统计不居中显示

### ISSUE THREAD

**Issue by heliuphy** [BearD01001/hexo-theme-nextd#2]
### Expected behavior (预期行为)
想让不蒜子统计在页脚居中显示。

### Actual behavior (实际行为)
不蒜子统计位置有些靠右。

### Other Informations (Like Browser, System, Screenshots)
Chrome,win10,[博客地址](https://heliublog.com)截屏如下：

![](http://op0n2nyjd.bkt.clouddn.com/github/issue/heliublog.com_1.jpg)

**Comment by BearD01001** [comment]
已修正

**Comment by heliuphy** [comment]
请问我更新主题的时候是直接`git pull`就可以了吗？这样会不会覆盖掉我修改过的配置文件呢？谢谢~

**Comment by BearD01001** [comment]
@heliuphy 可以先用 `git fetch` 然后 `merge` 一下就好了

**Comment by heliuphy** [comment]
好的，谢谢~
发自网易邮箱大师
在2017年06月17日 21:18，熊D01001 写道： @heliuphy 可以先用 git fetch 然后 merge 一下就好了

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/BearD01001/hexo-theme-nextd","title":"BearD01001/hexo-theme-nextd","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/BearD01001/hexo-theme-nextd"}},"updates":{"snippets":[{"icon":"PERSON","message":"@BearD01001 in #2: @heliuphy 可以先用 `git fetch` 然后 `merge` 一下就好了"}],"action":{"name":"View Issue","url":"https://github.com/BearD01001/hexo-theme-nextd/issues/2#issuecomment-309214702"}}}
